const chaptersWrap = document.getElementById("chapters");
HISTORIA.capitulos.forEach((c,i)=>{const section=document.createElement("section");section.className=`screen chapter chapter-${i+1}`;section.innerHTML=`<div class="chapter-shell"><figure class="story-photo ${i%2?"tilt-right":"tilt-left"}"><img src="${c.image}" alt="${c.caption}" draggable="false"><figcaption>${c.caption}</figcaption></figure><article class="story-copy"><span class="eyebrow">${c.kicker}</span><div class="year">${c.year}</div><h2>${c.title}</h2><p>${c.text}</p><button class="primary" data-next>Seguir recordando <span>→</span></button></article></div>`;chaptersWrap.appendChild(section)});
const gallery=document.getElementById("gallery");HISTORIA.album.forEach((src,i)=>{const card=document.createElement("figure");card.className="album-card";card.innerHTML=`<img src="${src}" alt="Recuerdo ${i+1}" draggable="false"><span>${String(i+1).padStart(2,"0")}</span>`;gallery.appendChild(card)});
let screens=[...document.querySelectorAll(".screen")],current=0,touchStartX=0,touchStartY=0;const progressBar=document.getElementById("progressBar"),stepCount=document.getElementById("stepCount"),backBtn=document.getElementById("backBtn");
function show(index){if(index<0||index>=screens.length)return;screens[current].classList.remove("active");current=index;screens[current].classList.add("active");progressBar.style.width=`${current/(screens.length-1)*100}%`;stepCount.textContent=`${String(current+1).padStart(2,"0")} / ${String(screens.length).padStart(2,"0")}`;backBtn.classList.toggle("invisible",current===0);if(screens[current].classList.contains("album-screen"))gallery.scrollTo({left:0,behavior:"instant"})}
document.addEventListener("click",e=>{if(e.target.closest("[data-next]"))show(current+1)});backBtn.addEventListener("click",()=>show(current-1));document.addEventListener("keydown",e=>{if(["ArrowRight","Enter"," "].includes(e.key))show(current+1);if(e.key==="ArrowLeft")show(current-1)});
document.addEventListener("touchstart",e=>{touchStartX=e.changedTouches[0].screenX;touchStartY=e.changedTouches[0].screenY},{passive:true});document.addEventListener("touchend",e=>{const dx=e.changedTouches[0].screenX-touchStartX,dy=e.changedTouches[0].screenY-touchStartY;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.35){if(dx<0)show(current+1);else show(current-1)}},{passive:true});
const albumCards=[...document.querySelectorAll(".album-card")],albumCounter=document.getElementById("albumCounter");function albumPosition(){const first=albumCards[0];if(!first)return 0;const unit=first.getBoundingClientRect().width+16;return Math.round(gallery.scrollLeft/unit)}function updateAlbumCounter(){const idx=Math.min(HISTORIA.album.length-1,Math.max(0,albumPosition()));albumCounter.textContent=`${String(idx+1).padStart(2,"0")} / ${String(HISTORIA.album.length).padStart(2,"0")}`}
document.getElementById("nextPhoto").addEventListener("click",()=>{const idx=Math.min(albumCards.length-1,albumPosition()+1);albumCards[idx].scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"})});document.getElementById("prevPhoto").addEventListener("click",()=>{const idx=Math.max(0,albumPosition()-1);albumCards[idx].scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"})});gallery.addEventListener("scroll",()=>requestAnimationFrame(updateAlbumCounter),{passive:true});
const music=document.getElementById("music"),soundBtn=document.getElementById("soundBtn");soundBtn.addEventListener("click",async()=>{try{if(music.paused){await music.play();soundBtn.classList.add("on")}else{music.pause();soundBtn.classList.remove("on")}}catch{soundBtn.textContent="♡";setTimeout(()=>soundBtn.textContent="♫",1200)}});
document.getElementById("emotionBtn").addEventListener("click",()=>{document.getElementById("emotionBtn").textContent="Ya… ahora sí 🥹❤️"});document.getElementById("yesBtn").addEventListener("click",()=>{document.getElementById("proposalActions").classList.add("hidden");document.getElementById("answer").classList.remove("hidden");for(let i=0;i<34;i++)setTimeout(makeHeart,i*70)});
function makeHeart(){const h=document.createElement("div");h.className="heart-float";h.textContent=Math.random()>.45?"♥":"♡";h.style.left=Math.random()*100+"vw";h.style.fontSize=14+Math.random()*28+"px";h.style.animationDuration=3+Math.random()*3+"s";document.body.appendChild(h);setTimeout(()=>h.remove(),6500)}setInterval(()=>{if(current===screens.length-1&&Math.random()>.58)makeHeart()},900);show(0);