const chapterImages = ["assets/photos/foto_03.jpg","assets/photos/foto_06.jpg","assets/photos/foto_01.jpg","assets/photos/foto_04.jpg","assets/photos/foto_09.jpg","assets/photos/foto_07.jpg","assets/photos/foto_08.jpg","assets/photos/foto_02.jpg"];
const galleryImages = ["assets/photos/foto_01.jpg","assets/photos/foto_02.jpg","assets/photos/foto_03.jpg","assets/photos/foto_04.jpg","assets/photos/foto_05.jpg","assets/photos/foto_06.jpg","assets/photos/foto_07.jpg","assets/photos/foto_08.jpg","assets/photos/foto_09.jpg"];
const chaptersWrap=document.getElementById("chapters");
HISTORIA.capitulos.forEach((c,i)=>{const section=document.createElement("section");section.className="screen chapter";section.innerHTML=`<div class="chapter-inner"><div class="chapter-copy"><span class="eyebrow">${c.kicker}</span><div class="year">${c.year}</div><h2>${c.title}</h2><p>${c.text}</p><button class="primary" data-next>Seguir recordando <span>→</span></button></div><div class="chapter-photo ${i%2?'polaroid':''}"><img src="${chapterImages[i]||galleryImages[i]||''}" alt="Recuerdo de nuestra historia"></div></div>`;chaptersWrap.appendChild(section)});
const gallery=document.getElementById("gallery");galleryImages.forEach((src,i)=>{const img=document.createElement("img");img.src=src;img.alt=`Recuerdo ${i+1}`;img.loading="lazy";gallery.appendChild(img)});
let screens=[...document.querySelectorAll(".screen")],current=0;
function show(index){if(index<0||index>=screens.length)return;screens[current].classList.remove("active");current=index;screens[current].classList.add("active");const pct=current/(screens.length-1)*100;document.getElementById("progressBar").style.width=pct+"%";document.getElementById("stepCount").textContent=`${String(current+1).padStart(2,"0")} / ${String(screens.length).padStart(2,"0")}`;if(screens[current].classList.contains("gallery-screen"))screens[current].scrollTop=0}
document.addEventListener("click",e=>{const b=e.target.closest("[data-next]");if(b)show(current+1)});
document.addEventListener("keydown",e=>{if(e.key==="ArrowRight"||e.key==="Enter")show(current+1);if(e.key==="ArrowLeft")show(current-1)});
const music=document.getElementById("music"),soundBtn=document.getElementById("soundBtn");soundBtn.addEventListener("click",async()=>{try{if(music.paused){await music.play();soundBtn.classList.add("on")}else{music.pause();soundBtn.classList.remove("on")}}catch{alert("Todavía falta agregar nuestra canción en assets/nuestra-cancion.mp3 ❤️")}});
document.getElementById("emotionBtn").addEventListener("click",()=>{document.getElementById("emotionBtn").textContent="Ok… ya estoy lista 🥹❤️"});
document.getElementById("yesBtn").addEventListener("click",()=>{document.getElementById("proposalActions").classList.add("hidden");document.getElementById("answer").classList.remove("hidden");for(let i=0;i<28;i++)setTimeout(makeHeart,i*85)});
function makeHeart(){const h=document.createElement("div");h.className="heart-float";h.textContent=Math.random()>.45?"♥":"♡";h.style.left=Math.random()*100+"vw";h.style.fontSize=14+Math.random()*24+"px";h.style.animationDuration=3+Math.random()*3+"s";document.body.appendChild(h);setTimeout(()=>h.remove(),6500)}
setInterval(()=>{if(current===screens.length-1&&Math.random()>.55)makeHeart()},900);show(0);